language: rust

rust:
- stable
- beta
- nightly

stages:
- lint
- test
- name: deploy
  if: branch = master

env:
  global:
  - RUST_BACKTRACE=1

# See http://www.garbers.co.za/2017/11/01/code-folding-and-timing-in-travis-ci/
before_script:
- export -f travis_nanoseconds
- export -f travis_fold
- export -f travis_time_start
- export -f travis_time_finish

matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
  include:
  - name: "stable lint"
    stage: lint
    rust: stable
    os: linux
    script: .ci/lint.sh
  - name: "beta lint"
    stage: lint
    rust: beta
    os: linux
    script: .ci/lint.sh

  - name: "stable test linux"
    stage: test
    rust: stable
    os: linux
    script: .ci/test.sh
  - name: "beta test linux"
    stage: test
    rust: beta
    os: linux
    script: .ci/test.sh
  - name: "nightly test linux"
    stage: test
    rust: nightly
    script: .ci/test.sh
  - name: "stable test osx"
    rust: stable
    os: osx
    script: .ci/test.sh
  - name: "stable test windows"
    rust: stable
    os: windows
    script: .ci/test.sh

  