
# cargo-vet config file

[cargo-vet]
version = "0.8"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.firefox]
url = "https://hg.mozilla.org/mozilla-central/raw-file/tip/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.wasmtime]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.cargo-deny]
audit-as-crates-io = false

[policy.errno-dragonfly]
criteria = []
notes = "Not used, unsupported target"

[policy.js-sys]
criteria = []
notes = "Not used, web WASM-only"

[policy.wasi]
criteria = []
notes = "Not used, unsupported target"

[policy.wasm-bindgen]
criteria = []
notes = "Not used, web WASM-only"

[policy.wasm-bindgen-backend]
criteria = []
notes = "Not used, web WASM-only"

[policy.wasm-bindgen-macro]
criteria = []
notes = "Not used, web WASM-only"

[policy.wasm-bindgen-macro-support]
criteria = []
notes = "Not used, web WASM-only"

[[exemptions.addr2line]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.75"
criteria = "safe-to-deploy"

[[exemptions.arc-swap]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.arrayvec]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.askalono]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.async-compression]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.69"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.btoi]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.camino]]
version = "1.1.6"
criteria = "safe-to-deploy"

[[exemptions.cargo-lock]]
version = "9.0.0"
criteria = "safe-to-deploy"

[[exemptions.cargo-platform]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.83"
criteria = "safe-to-deploy"

[[exemptions.clru]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.codespan]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.console]]
version = "0.15.7"
criteria = "safe-to-run"

[[exemptions.cpufeatures]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.6"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.cvss]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.dunce]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.encode_unicode]]
version = "0.3.6"
criteria = "safe-to-run"

[[exemptions.equivalent]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.faster-hex]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.fern]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.fixedbitset]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.flate2]]
version = "1.0.27"
criteria = "safe-to-deploy"

[[exemptions.form_urlencoded]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.fs-err]]
version = "2.8.1"
criteria = "safe-to-deploy"

[[exemptions.fs_extra]]
version = "1.3.0"
criteria = "safe-to-run"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.26.1"
criteria = "safe-to-deploy"

[[exemptions.gix]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.gix-actor]]
version = "0.25.0"
criteria = "safe-to-deploy"

[[exemptions.gix-attributes]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.gix-bitmap]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.gix-chunk]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.gix-command]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.gix-commitgraph]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.gix-config]]
version = "0.28.0"
criteria = "safe-to-deploy"

[[exemptions.gix-config-value]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.gix-credentials]]
version = "0.18.0"
criteria = "safe-to-deploy"

[[exemptions.gix-date]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.gix-diff]]
version = "0.34.0"
criteria = "safe-to-deploy"

[[exemptions.gix-discover]]
version = "0.23.0"
criteria = "safe-to-deploy"

[[exemptions.gix-features]]
version = "0.33.0"
criteria = "safe-to-deploy"

[[exemptions.gix-filter]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.gix-fs]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.gix-glob]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.gix-hash]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.gix-hashtable]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.gix-ignore]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.gix-index]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.gix-lock]]
version = "8.0.0"
criteria = "safe-to-deploy"

[[exemptions.gix-mailmap]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.gix-negotiate]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.gix-object]]
version = "0.35.0"
criteria = "safe-to-deploy"

[[exemptions.gix-odb]]
version = "0.51.0"
criteria = "safe-to-deploy"

[[exemptions.gix-pack]]
version = "0.41.0"
criteria = "safe-to-deploy"

[[exemptions.gix-packetline]]
version = "0.16.5"
criteria = "safe-to-deploy"

[[exemptions.gix-packetline-blocking]]
version = "0.16.5"
criteria = "safe-to-deploy"

[[exemptions.gix-path]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.gix-pathspec]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.gix-prompt]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.gix-protocol]]
version = "0.38.0"
criteria = "safe-to-deploy"

[[exemptions.gix-quote]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.gix-ref]]
version = "0.35.0"
criteria = "safe-to-deploy"

[[exemptions.gix-refspec]]
version = "0.16.0"
criteria = "safe-to-deploy"

[[exemptions.gix-revision]]
version = "0.20.0"
criteria = "safe-to-deploy"

[[exemptions.gix-revwalk]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.gix-sec]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.gix-submodule]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.gix-tempfile]]
version = "8.0.0"
criteria = "safe-to-deploy"

[[exemptions.gix-trace]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.gix-transport]]
version = "0.35.0"
criteria = "safe-to-deploy"

[[exemptions.gix-traverse]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.gix-url]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.gix-utils]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.gix-validate]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.gix-worktree]]
version = "0.24.0"
criteria = "safe-to-deploy"

[[exemptions.gix-worktree-state]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.goblin]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.home]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.httpdate]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.25"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.24.1"
criteria = "safe-to-deploy"

[[exemptions.imara-diff]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.1"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.insta]]
version = "1.31.0"
criteria = "safe-to-run"

[[exemptions.io-close]]
version = "0.3.7"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.jwalk]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.126"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.10"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.20"
criteria = "safe-to-deploy"

[[exemptions.maybe-async]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.memmap2]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "7.1.1"
criteria = "safe-to-deploy"

[[exemptions.nu-ansi-term]]
version = "0.49.0"
criteria = "safe-to-deploy"

[[exemptions.num_threads]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.28.4"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.11.2"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.petgraph]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.13"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.plain]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.platforms]]
version = "3.1.2"
criteria = "safe-to-deploy"

[[exemptions.prodash]]
version = "25.0.2"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.33"
criteria = "safe-to-deploy"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.reqwest]]
version = "0.11.20"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.16.20"
criteria = "safe-to-deploy"

[[exemptions.rmp]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.rmp-serde]]
version = "0.14.4"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.21.7"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.rustsec]]
version = "0.28.0"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.22"
criteria = "safe-to-deploy"

[[exemptions.scroll]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.scroll_derive]]
version = "0.10.5"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.9.2"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.9.1"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.sha1_smol]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.signal-hook]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.smol_str]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.static_assertions]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.strum]]
version = "0.25.0"
criteria = "safe-to-deploy"

[[exemptions.strum_macros]]
version = "0.25.2"
criteria = "safe-to-deploy"

[[exemptions.tame-index]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.8.0"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.47"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.47"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.32.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.24.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.34"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.28"
criteria = "safe-to-deploy"

[[exemptions.twox-hash]]
version = "1.6.3"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-bom]]
version = "2.0.2"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.37"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.64"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.45.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.42.2"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.winreg]]
version = "0.50.0"
criteria = "safe-to-deploy"

[[exemptions.wyz]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.zstd]]
version = "0.11.2+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-safe]]
version = "5.0.2+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-sys]]
version = "2.0.8+zstd.1.5.5"
criteria = "safe-to-deploy"
