
# cargo-vet config file

[cargo-vet]
version = "0.7"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.firefox]
url = "https://hg.mozilla.org/mozilla-central/raw-file/tip/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.wasmtime]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.cargo-deny]
audit-as-crates-io = false

[policy.errno-dragonfly]
criteria = []
notes = "Not used, unsupported target"

[policy.js-sys]
criteria = []
notes = "Not used, web WASM-only"

[policy.wasi]
criteria = []
notes = "Not used, unsupported target"

[policy.wasm-bindgen]
criteria = []
notes = "Not used, web WASM-only"

[policy.wasm-bindgen-backend]
criteria = []
notes = "Not used, web WASM-only"

[policy.wasm-bindgen-macro]
criteria = []
notes = "Not used, web WASM-only"

[policy.wasm-bindgen-macro-support]
criteria = []
notes = "Not used, web WASM-only"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.arrayvec]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.askalono]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.base16ct]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitmaps]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.bytesize]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.cargo]]
version = "0.69.1"
criteria = "safe-to-deploy"

[[exemptions.cargo-lock]]
version = "8.0.3"
criteria = "safe-to-deploy"

[[exemptions.cargo-util]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.79"
criteria = "safe-to-deploy"

[[exemptions.codespan]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.combine]]
version = "4.6.6"
criteria = "safe-to-deploy"

[[exemptions.commoncrypto]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.commoncrypto-sys]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.crates-io]]
version = "0.35.1"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.6"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.crypto-bigint]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.crypto-hash]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.ct-codecs]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.curl]]
version = "0.4.44"
criteria = "safe-to-deploy"

[[exemptions.cvss]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.ecdsa]]
version = "0.16.2"
criteria = "safe-to-deploy"

[[exemptions.ed25519-compact]]
version = "2.0.4"
criteria = "safe-to-deploy"

[[exemptions.elliptic-curve]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.encode_unicode]]
version = "0.3.6"
criteria = "safe-to-run"

[[exemptions.env_logger]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.fern]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.ff]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.fixedbitset]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.flate2]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.fs-err]]
version = "2.8.1"
criteria = "safe-to-deploy"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.fwdansi]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.group]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.hex]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.hkdf]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.hmac]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.home]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.http-auth]]
version = "0.1.8"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.im-rc]]
version = "15.1.0"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.1"
criteria = "safe-to-deploy"

[[exemptions.insta]]
version = "1.29.0"
criteria = "safe-to-run"

[[exemptions.instant]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-deploy"

[[exemptions.lazycell]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.140"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.miow]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.nu-ansi-term]]
version = "0.47.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.opener]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.openssl]]
version = "0.10.49"
criteria = "safe-to-deploy"

[[exemptions.openssl-macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.openssl-sys]]
version = "0.9.84"
criteria = "safe-to-deploy"

[[exemptions.ordered-float]]
version = "2.10.0"
criteria = "safe-to-deploy"

[[exemptions.orion]]
version = "0.17.4"
criteria = "safe-to-deploy"

[[exemptions.os_info]]
version = "3.7.0"
criteria = "safe-to-deploy"

[[exemptions.p384]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.pasetors]]
version = "0.6.6"
criteria = "safe-to-deploy"

[[exemptions.pathdiff]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.pem-rfc7468]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.petgraph]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.platforms]]
version = "3.0.2"
criteria = "safe-to-deploy"

[[exemptions.primeorder]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.rand_xoshiro]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.13"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.rfc6979]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.rmp]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.rmp-serde]]
version = "0.14.4"
criteria = "safe-to-deploy"

[[exemptions.rustfix]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.rustsec]]
version = "0.26.5"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.21"
criteria = "safe-to-deploy"

[[exemptions.sec1]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.serde-value]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.9.9"
criteria = "safe-to-deploy"

[[exemptions.shell-escape]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.signature]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.sized-chunks]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.smol_str]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.static_assertions]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.strip-ansi-escapes]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.strum_macros]]
version = "0.24.3"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.20"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.twox-hash]]
version = "1.6.3"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-bidi]]
version = "0.3.13"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.vte]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.vte_generate_state_changes]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.wyz]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.4.3"
criteria = "safe-to-deploy"

[[exemptions.zstd]]
version = "0.11.2+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-safe]]
version = "5.0.2+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-sys]]
version = "2.0.7+zstd.1.5.4"
criteria = "safe-to-deploy"
