[book]
authors = ["Jake Shadle"]
language = "en"
src = "src"
title = "cargo-deny"

[output.html]

# [output.linkcheck2]
# optional = true
# follow-web-links = true
# warning-policy = "warn"
# exclude = ['placehold\.it']
#
# [output.linkcheck2.http-headers]
# # Any hyperlink that contains this regexp will be sent
# # the "Accept: text/html" header
# 'crates\.io' = ["Accept: text/html"]
