[package]
name = "deny-copyleft"
version = "0.1.0"
authors = ["Jake Shadle <jake.shadle@embark-studios.com>"]
license = "GPL-3.0 AND MIT"
edition = "2018"

[[bin]]
name = "deny-copyleft"
path = "main.rs"
