[package]
name = "non-updatable"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
# ammonia had a stack overflow < 2.1.0
# https://github.com/RustSec/advisory-db/blob/01ac6725d549dbc7873250fe2a55e54d528fe945/crates/ammonia/RUSTSEC-2019-0001.toml
# Since we explicitly pin to this version, it won't be updatable
ammonia-bad = { version = "=0.7.0", package = "ammonia" }

# Transitively depends on an ammonia 1.2.0, not updatable
artifact_serde = "0.3.1"

[dev-dependencies]
ammonia = "1.2.0"

[workspace]
